log:
  level: info
  format: json
  output: stdout
auth:
  jwt:
    trustedIssuerUrls:
      - http://127.0.0.1:8081
    claimsCache:
      enabled: true
      maxEntries: 1000
  introspection:
    enabled: true